server:
  context-path: /mpserver
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mpdemo?characterEncoding=utf-8&useSSL=true&allowMultiQueries=true
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
  mvc:
    view:
      prefix: /templates/
      suffix: .ftl
  freemarker:
    cache: false
    request-context-attribute: request
  jackson:
#    default-property-inclusion: non_null



#HoistTheSails公众号管理
wechat:
  mp:
    appId: wx089e473e49a0b9bc
    appSecret: 9b477fe08f7796150833276a419906f2
  server:
    url:
    token:
    encodingAESKey:
  pay:
    mchId:
    mchKey:
    keyPath:
    notifyUrl:
  open:
    appId:
    appSecret:

#mybatis配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
#  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.muyi.mpdemo.view

mapper:
    mappers:
        - com.muyi.mpdemo.utils.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


