server:
  context-path: /mpserver
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mpdemo?useSSL=true&allowMultiQueries=true
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
  mvc:
    view:
      prefix: /templates/
      suffix: .ftl
    static-path-pattern: /static/**
  freemarker:
    cache: false
    request-context-attribute: request
  jackson:
#    default-property-inclusion: non_null

#
project:
  url:
    index: http://muyi.natapp1.cc/mpserver/index
    authUserInfo: http://muyi.natapp1.cc/mpserver/wechat/web/userInfo
    webAuth: http://muyi.natapp1.cc/mpserver/wechat/web/authorize

#公众平台借用账号 估计只能用于支付测试
wechat:
  mp:
    appId: wxd898fcb01713c658
    appSecret: xxxxxxxxxxxxxx
#  server:
#    url: http://muyi.natapp1.cc/mpserver/wechat/portal
#    token: muyimptoken
#    encodingAESKey: gnJTQGs6Hwz6CnmScUYQM6TOyijeKx9bfZ4mYUeMMIU
  pay:
    mchId: 1483469312
    mchKey: C5245D70627C1F8E9964D494B0735025
    keyPath: classpath:h5.p12
    notifyUrl:  http://xxx.com/notify
  open:
    appId: wx6ad144e54af67d87
    appSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e

#mybatis配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
#  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.muyi.mpdemo.domain

#通用mapper
mapper:
    mappers:
        - com.muyi.mpdemo.frame.MyMapper
    not-empty: false
    identity: MYSQL

#mybatis分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


